//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultyAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectFaculty : DbContext
    {
        public ConnectFaculty()
            : base("name=ConnectFaculty")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<BatchCourseFacultyMapping> BatchCourseFacultyMappings { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<DeliveryModel> DeliveryModels { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Grader> Graders { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<FacultyCourseMapping> FacultyCourseMappings { get; set; }
    }
}
